import React from 'react'

export const MyAccount = () => {
  return (
    <div>
        MyAccount Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt suscipit voluptates illo autem numquam, recusandae iste mollitia aperiam earum! Pariatur quasi dolor similique laborum eveniet, obcaecati vitae beatae facilis! Reprehenderit explicabo enim libero quasi, atque ipsam necessitatibus cupiditate sequi nostrum, iusto praesentium, est hic nobis quo aliquam ratione et quis alias. Sequi quasi alias error dicta a deserunt perspiciatis, illum, corporis nesciunt tempora officia nihil ratione, aliquid earum quae praesentium qui possimus nulla eaque! Corrupti, voluptatum debitis! Laborum consequuntur debitis quisquam illo illum voluptatum reprehenderit id dolorem expedita autem. Nihil ipsum placeat illo? Ut quasi repellat, maxime sunt pariatur, sequi tempora quibusdam dolor doloremque similique nemo quia quo repellendus id obcaecati enim, in quisquam. Sed dicta suscipit, a provident quaerat dolore doloribus? Officiis accusamus officia corrupti voluptas quod, quam sequi numquam natus et dolore tempora ipsa porro accusantium minima, explicabo libero aliquid molestiae beatae quidem praesentium atque odio. Soluta, expedita? Tempore tenetur voluptatum ad provident nihil ea consequatur velit dolorum libero id recusandae fuga sunt magni perferendis quae, sapiente officia, doloremque rerum voluptas, eos maxime accusamus. Porro incidunt pariatur suscipit voluptate voluptatum autem totam expedita libero, iure sequi tenetur blanditiis ducimus quae nemo praesentium, nihil officia aliquam necessitatibus? Magnam eaque fugiat deserunt labore itaque. Earum dolore tenetur, nobis quidem a voluptas. Non commodi quibusdam, quas rerum incidunt, corrupti accusamus animi id cum aperiam libero optio maxime deleniti eaque ducimus mollitia modi esse placeat unde consectetur quidem eum? Doloremque, blanditiis at molestias, sed culpa fugit quisquam fugiat ad dolore similique labore?
    </div>
  )
}
